### ISSUE TITLE
Should I add Reverse engineered code snippets to the broma file if I know exactly what is going on?

### ISSUE THREAD

**Issue by CallocGD** [geode-sdk/bindings#210]
I have a [repository](https://github.com/CallocGD/GD-2.2-Decompiled) where I keep some 2.2 reverse engineered snippets I did after I forked Wyliemaster's own repository (Until he finally makes a 2.2 repository of his own) so I could explore some major components that were missing and that I wanted to learn more about.

So, I was wondering if it would be a good Idea to try and merge any reverse engineered code I find once I've changed the class member names to reflect the names provided by broma files. I feel like modders should know what is going on under the hood which is why I am asking about this now rather than later...

I have an example for a function I wanted to add (If it hasn't been done already) however it should be noted that these are not inline functions.
```c++
bool GameManager::getGameVariable(char * key){
    return m_pGameVariableDict->valueForKey(key)->boolValue();
}
```

**Comment by poweredbypie** [comment]
no. if they are already existing in GD there is no reason to provide this information. perhaps this would be useful in the feature but this repo is for *bindings*, not to provide insight into how functions work
