### ISSUE TITLE
update failed

### ISSUE THREAD

**Issue by tf2enjoyer-lolsquare** [geode-sdk/bindings#582]
so i was using geode 2.205 and then i heard the android launcher now supports 2.206 so i download it from geode-sdk.org
i open geode then:

![Screenshot_20240625-174509_Geode](https://github.com/geode-sdk/bindings/assets/173788784/3138e47d-1ee2-4af6-9c90-9b3633a25ec0)

i dont see any other person that has this issue. geode for 2.2.05 also failed too. maybe its my device or something

**Comment by tf2enjoyer-lolsquare** [comment]
`e`

**Comment by qimiko** [comment]
how did you end up in bindings.

**Comment by tf2enjoyer-lolsquare** [comment]
what is a bindings?
